### ISSUE TITLE
No throttle control

### ISSUE THREAD

**Issue by Helldiver1080** [SheepCreativeSoftware/msfs2020-C208-Improvment-Mod#157]
When trying to run the game, throttle is either 100% full or full reverse, cannot control it otherwise. Using an Xbox one controller

**To Reproduce**
1. Choose 208 as airplane
2. load into flight
3. press A and B to test throttle

**Expected behavior**
Throttle increments up and down based on buttons hit. 

Removal of the mod restores normal behavior, currently not using other mods

**Comment by tonythestrabest** [comment]
I confirm. I heave Saitek throttle. All  trhree levers goes from  100 % to reverse, feather and cut off respectively. I tried several (more than 10) configurations. No way to make them work properly. I noted that even black square analog caravan had the same problem with the mod installed. Once  the mod is removed black square throttle work properly.

**Comment by Ambu121** [comment]
Have the same problem like @Natervater
I am using a Xbox 360 controller.
There is only 100% thrust and reverse thrust.

How do I fix that ? :(

**Comment by Helldiver1080** [comment]
Unfortunately I don't believe we are going to get an answer here. Best option would be to remove the mod as that restores the caravan back to normal.

**Comment by magraina** [comment]
@NewoPL did you saw that?

**Comment by NewoPL** [comment]
let me test that. it may be connected with the throttle axis that is assigned.

**Comment by NewoPL** [comment]
the fix is available on the branch here: https://codeload.github.com/NewoPL/msfs2020-C208-Improvment-Mod/zip/refs/heads/release
to install unpack the above archive, copy c208B-mod subfolder to msfs community folder
please test

**Comment by Ambu121** [comment]
> the fix is available on the branch here: https://codeload.github.com/NewoPL/msfs2020-C208-Improvment-Mod/zip/refs/heads/release to install unpack the above archive, copy c208B-mod subfolder to msfs community folder please test

Hi,
thank you for your answer.

The problem is still there.

Do I need to change or bind throttle buttons / axis ?

**Comment by NewoPL** [comment]
My bad - I gave you a wrong link. Fixed version is here:
https://codeload.github.com/NewoPL/msfs2020-C208-Improvment-Mod/zip/refs/heads/experimental
You should not use any axis, according to the bug description problem was with incremental throttle setting through A/B buttons.  That should work now at least in my tests. Please remember that you need to copy c208b-mod subfolder to community folder.

**Comment by Helldiver1080** [comment]
@NewoPL Testing this now, will report back

**Comment by Helldiver1080** [comment]
@NewoPL Same issue. Cannot control throttle with A and B, it goes from idle to full in 1 button press

I appreciate you trying to figure it out, thank you

**Comment by Helldiver1080** [comment]
Correction to my previous post, i reset my keybinds and SUDDENLY it started working. Still testing and will report back

**Comment by ghost** [comment]
> Correction to my previous post, i reset my keybinds and SUDDENLY it started working. Still testing and will report back.

Before starting the sim, type joy.cpl in Windows Start and check the calibration of the hardware. Recalibration will solve the jumping throttle issue.
Jan-KLM149
